-- ANALYTICAL QUERIES

-- Set active warehouse
USE WAREHOUSE MTS_WAREHOUSE;
USE DATABASE MTS_DATABASE;
USE SCHEMA MTS_SCHEMA;


-- DAILY TRANSACTIONS VOLUME

SELECT
  DATE(CREATED_ON)               AS TXN_DATE,
  COUNT(*)                       AS TXN_COUNT,
  SUM(AMOUNT)                    AS TOTAL_AMOUNT
FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
GROUP BY TXN_DATE
ORDER BY TXN_DATE;


-- MOST ACTIVE ACCOUNTS

WITH FROM_ACCT AS (
  SELECT FROM_ACCOUNT_ID AS ACCT, COUNT(*) AS C
  FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
  GROUP BY FROM_ACCOUNT_ID
),
TO_ACCT AS (
  SELECT TO_ACCOUNT_ID AS ACCT, COUNT(*) AS C
  FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
  GROUP BY TO_ACCOUNT_ID
),
COMBINED AS (
  SELECT ACCT, C FROM FROM_ACCT
  UNION ALL
  SELECT ACCT, C FROM TO_ACCT
)
 
SELECT
  ACCT                         AS ACCOUNT_ID,
  SUM(C)                       AS TOTAL_INTERACTIONS
FROM COMBINED
GROUP BY ACCOUNT_ID
ORDER BY TOTAL_INTERACTIONS DESC, ACCOUNT_ID
LIMIT 10;

-- BUSIEST TRANSACTION HOURS

 SELECT
  DATE_PART('HOUR', CREATED_ON) AS HOUR_OF_DAY,
  COUNT(*)                      AS TXN_COUNT
FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
GROUP BY HOUR_OF_DAY
ORDER BY TXN_COUNT DESC, HOUR_OF_DAY
LIMIT 5;

-- AVERAGE TRANSFER AMOUNT PER DAY

SELECT
  DATE(CREATED_ON)      AS TXN_DATE,
  AVG(AMOUNT)           AS AVG_TRANSFER_AMOUNT
FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
GROUP BY TXN_DATE
ORDER BY TXN_DATE;


-- PERCENTAGE OF SUCCESSFUL TRANSACTIONS PER DAY

SELECT
  DATE(CREATED_ON)                                      AS TXN_DATE,
  COUNT(*)                                              AS TOTAL,
  SUM(IFF(STATUS = 1, 1, 0))                            AS SUCCESSES,
  ROUND(100 * SUM(IFF(STATUS = 1, 1, 0)) / NULLIF(COUNT(*), 0), 2)
                                                        AS SUCCESS_RATE_PCT
FROM MTS_DATABASE.MTS_SCHEMA.TRANSACTIONS
GROUP BY TXN_DATE
ORDER BY TXN_DATE;
 